const parameters = {
  typeData: {
    topHeadlines: 'top-headlines',
    everything: 'everything',
    sources: 'sources',
  },
  country: 'country',
  category: 'category',
  sources: 'sources',
  pageSize: 'pageSize',
  q: 'q',
  defaultParams: {
    country: 'us',
    category: 'general',
    pageSize: '20',
  },
  choose: {
    country: 'Choose country',
    category: 'Choose category',
    pageSize: 'Page size',
  },
  countries: {
    ae: 'United Arab Emirates',
    ar: 'Argentina',
    at: 'Austria',
    au: 'Australia',
    be: 'Belgium',
    bg: 'Bulgaria',
    br: 'Brazil',
    ca: 'Canada',
    ch: 'Switzerland',
    cn: 'China',
    co: 'Colombia',
    cu: 'Cuba',
    cz: 'Czech Republic',
    de: 'Germany',
    eg: 'Egypt',
    fr: 'France',
    gb: 'United Kingdom',
    gr: 'Greece',
    hk: 'Hong Kong, SAR China',
    hu: 'Hungary',
    id: 'Indonesia',
    ie: 'Ireland',
    il: 'Israel',
    in: 'India',
    it: 'Italy',
    jp: 'Japan',
    kr: 'Korea (South)',
    lt: 'Lithuania',
    lv: 'Latvia',
    ma: 'Morocco',
    mx: 'Mexico',
    my: 'Malaysia',
    ng: 'Nigeria',
    nl: 'Netherlands',
    no: 'Norway',
    nz: 'New Zealand',
    ph: 'Philippines',
    pl: 'Poland',
    pt: 'Portugal',
    ro: 'Romania',
    rs: 'Serbia',
    ru: 'Russian Federation',
    sa: 'Saudi Arabia',
    se: 'Sweden',
    sg: 'Singapore',
    si: 'Slovenia',
    sk: 'Slovakia',
    th: 'Thailand',
    tr: 'Turkey',
    tw: 'Taiwan, Republic of China',
    ua: 'Ukraine',
    us: 'United States of America',
    ve: 'Venezuela (Bolivarian Republic)',
    za: 'South Africa',
  },
  categories: {
    business: 'Business',
    entertainment: 'Entertainment',
    general: 'General',
    health: 'Health',
    science: 'Science',
    sports: 'Sports',
    technology: 'Technology',
  },
  pageSizes: {
    1: 1,
    5: 5,
    10: 10,
    20: 20,
    50: 50,
    100: 100,
  },
};

export default parameters;
